#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

REG="^([0-9]{1,3}\.){3}[0-9]{1,3}$"
REGT="\[TicketNo:\].[a-zA-Z0-9;]{1,}\W\[Description:\][\s\S]*\W\[Binary\WSource:\].*"

MSG=$(cat $1) # \[TicketNo:\].[a-zA-Z0-9;]{1,}\W\[Description:\][\s\S]*\W\[Binary\WSource:\].*

MSGT="[TicketNo:]AR10092[Description:]哈哈[Binary Source:]NA"

newip='192.168.1.1' # ^([0-9]{1,3}\.){3}[0-9]{1,3}$

if [[ $MSGT =~ $REGT ]]; then
    echo "success"
fi

exit 1
